@extends('layout.app')
@section('css')
@endsection
@section('home')
    @include('page.pages.home')
@endsection
@section('about')
    @include('page.pages.about')
@endsection
@section('about')
    @include('page.pages.about')
@endsection
@section('gallery')
    @include('page.pages.gallery')
@endsection
@section('contact')
    @include('page.pages.contact')
@endsection
@section('js')
@endsection